import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Montserrat } from "next/font/google";

import "@/app/globals.css";
import Sidenav from "./components/sidenav";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const ms = Montserrat({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${ms.className} `}>
                <div className="w-screen h-screen flex">
                    <Sidenav />
                    <div className=" h-full w-full ">{children}</div>
                </div>
            </body>
        </html>
    );
}
